//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 
namespace Proxy.ProxyCirugiaPersonalQ {
    /// <remarks/>
    // CODEGEN: No methods were found in the WSDL for this protocol.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioCirugiaPersonalQSoap", Namespace="http://tempuri.org/")]
    public partial class ServicioCirugiaPersonalQ : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ServicioCirugiaPersonalQ() {
            this.Url = "http://190.200.157.130/ServiciosCeclimi/ServicioCirugiaPersonalQ.asmx";
        }
    }
}
