//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.4927
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

namespace Proxy.ProxyCirugiaPersonalQ
{ // 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioCirugiaPersonalQSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Entidad))]
    public partial class ServicioCirugiaPersonalQ : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
        private System.Threading.SendOrPostCallback AgregarCirugiaPersonalQOperationCompleted;
    
        private System.Threading.SendOrPostCallback ObtenerPersonalQOperationCompleted;
    
        /// <remarks/>
        public ServicioCirugiaPersonalQ() {
            this.Url = "http://192.168.1.109/ServiciosCeclimi/ServicioCirugiaPersonalQ.asmx";
        }
    
        /// <remarks/>
        public event AgregarCirugiaPersonalQCompletedEventHandler AgregarCirugiaPersonalQCompleted;
    
        /// <remarks/>
        public event ObtenerPersonalQCompletedEventHandler ObtenerPersonalQCompleted;
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarCirugiaPersonalQ", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AgregarCirugiaPersonalQ(PersonalPaquete personalPaquete) {
            object[] results = this.Invoke("AgregarCirugiaPersonalQ", new object[] {
                                                                                       personalPaquete});
            return ((bool)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BeginAgregarCirugiaPersonalQ(PersonalPaquete personalPaquete, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AgregarCirugiaPersonalQ", new object[] {
                                                                                personalPaquete}, callback, asyncState);
        }
    
        /// <remarks/>
        public bool EndAgregarCirugiaPersonalQ(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    
        /// <remarks/>
        public void AgregarCirugiaPersonalQAsync(PersonalPaquete personalPaquete) {
            this.AgregarCirugiaPersonalQAsync(personalPaquete, null);
        }
    
        /// <remarks/>
        public void AgregarCirugiaPersonalQAsync(PersonalPaquete personalPaquete, object userState) {
            if ((this.AgregarCirugiaPersonalQOperationCompleted == null)) {
                this.AgregarCirugiaPersonalQOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarCirugiaPersonalQOperationCompleted);
            }
            this.InvokeAsync("AgregarCirugiaPersonalQ", new object[] {
                                                                         personalPaquete}, this.AgregarCirugiaPersonalQOperationCompleted, userState);
        }
    
        private void OnAgregarCirugiaPersonalQOperationCompleted(object arg) {
            if ((this.AgregarCirugiaPersonalQCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarCirugiaPersonalQCompleted(this, new AgregarCirugiaPersonalQCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerPersonalQ", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Personal[] ObtenerPersonalQ() {
            object[] results = this.Invoke("ObtenerPersonalQ", new object[0]);
            return ((Personal[])(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BeginObtenerPersonalQ(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ObtenerPersonalQ", new object[0], callback, asyncState);
        }
    
        /// <remarks/>
        public Personal[] EndObtenerPersonalQ(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Personal[])(results[0]));
        }
    
        /// <remarks/>
        public void ObtenerPersonalQAsync() {
            this.ObtenerPersonalQAsync(null);
        }
    
        /// <remarks/>
        public void ObtenerPersonalQAsync(object userState) {
            if ((this.ObtenerPersonalQOperationCompleted == null)) {
                this.ObtenerPersonalQOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPersonalQOperationCompleted);
            }
            this.InvokeAsync("ObtenerPersonalQ", new object[0], this.ObtenerPersonalQOperationCompleted, userState);
        }
    
        private void OnObtenerPersonalQOperationCompleted(object arg) {
            if ((this.ObtenerPersonalQCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerPersonalQCompleted(this, new ObtenerPersonalQCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonalPaquete : Entidad {
    
        private string especialidadField;
    
        private CirugiaPqtFinanciero cirugiaField;
    
        private Persona personalField;
    
        /// <comentarios/>
        public string Especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
            }
        }
    
        /// <comentarios/>
        public CirugiaPqtFinanciero Cirugia {
            get {
                return this.cirugiaField;
            }
            set {
                this.cirugiaField = value;
            }
        }
    
        /// <comentarios/>
        public Persona Personal {
            get {
                return this.personalField;
            }
            set {
                this.personalField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CirugiaPqtFinanciero : Entidad {
    
        private float montoCirujanoField;
    
        private float descuentoField;
    
        private Cirujano cirujanoField;
    
        private System.DateTime fechaOperacionField;
    
        private Cirugia cirugiaField;
    
        private PaqueteFinanciero paqueteFinancieroField;
    
        private float protesisField;
    
        /// <comentarios/>
        public float MontoCirujano {
            get {
                return this.montoCirujanoField;
            }
            set {
                this.montoCirujanoField = value;
            }
        }
    
        /// <comentarios/>
        public float Descuento {
            get {
                return this.descuentoField;
            }
            set {
                this.descuentoField = value;
            }
        }
    
        /// <comentarios/>
        public Cirujano Cirujano {
            get {
                return this.cirujanoField;
            }
            set {
                this.cirujanoField = value;
            }
        }
    
        /// <comentarios/>
        public System.DateTime FechaOperacion {
            get {
                return this.fechaOperacionField;
            }
            set {
                this.fechaOperacionField = value;
            }
        }
    
        /// <comentarios/>
        public Cirugia Cirugia {
            get {
                return this.cirugiaField;
            }
            set {
                this.cirugiaField = value;
            }
        }
    
        /// <comentarios/>
        public PaqueteFinanciero PaqueteFinanciero {
            get {
                return this.paqueteFinancieroField;
            }
            set {
                this.paqueteFinancieroField = value;
            }
        }
    
        /// <comentarios/>
        public float Protesis {
            get {
                return this.protesisField;
            }
            set {
                this.protesisField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cirujano : Persona {
    
        private string telefonoMovilField;
    
        private string telefonoFijoField;
    
        /// <comentarios/>
        public string TelefonoMovil {
            get {
                return this.telefonoMovilField;
            }
            set {
                this.telefonoMovilField = value;
            }
        }
    
        /// <comentarios/>
        public string TelefonoFijo {
            get {
                return this.telefonoFijoField;
            }
            set {
                this.telefonoFijoField = value;
            }
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Personal))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cirujano))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Paciente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Persona : Entidad {
    
        private long cedulaField;
    
        private string segundoNombreField;
    
        private string primerApellidoField;
    
        private string segundoApellidoField;
    
        private string telefonoField;
    
        private string correoField;
    
        /// <comentarios/>
        public long Cedula {
            get {
                return this.cedulaField;
            }
            set {
                this.cedulaField = value;
            }
        }
    
        /// <comentarios/>
        public string SegundoNombre {
            get {
                return this.segundoNombreField;
            }
            set {
                this.segundoNombreField = value;
            }
        }
    
        /// <comentarios/>
        public string PrimerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
            }
        }
    
        /// <comentarios/>
        public string SegundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
            }
        }
    
        /// <comentarios/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
    
        /// <comentarios/>
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PaqueteFinanciero))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cirugia))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Persona))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Personal))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cirujano))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Paciente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CirugiaPqtFinanciero))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonalPaquete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Entidad {
    
        private long idField;
    
        private string nombreField;
    
        /// <comentarios/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PaqueteFinanciero : Entidad {
    
        private System.DateTime fechaPaqueteField;
    
        private System.DateTime fechaLimiteField;
    
        private Paciente pacienteField;
    
        /// <comentarios/>
        public System.DateTime FechaPaquete {
            get {
                return this.fechaPaqueteField;
            }
            set {
                this.fechaPaqueteField = value;
            }
        }
    
        /// <comentarios/>
        public System.DateTime FechaLimite {
            get {
                return this.fechaLimiteField;
            }
            set {
                this.fechaLimiteField = value;
            }
        }
    
        /// <comentarios/>
        public Paciente Paciente {
            get {
                return this.pacienteField;
            }
            set {
                this.pacienteField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Paciente : Persona {
    
        private System.DateTime fechaIngresoField;
    
        private string telefonoMovilField;
    
        /// <comentarios/>
        public System.DateTime FechaIngreso {
            get {
                return this.fechaIngresoField;
            }
            set {
                this.fechaIngresoField = value;
            }
        }
    
        /// <comentarios/>
        public string TelefonoMovil {
            get {
                return this.telefonoMovilField;
            }
            set {
                this.telefonoMovilField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cirugia : Entidad {
    
        private string descripcionField;
    
        /// <comentarios/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Personal : Persona {
    
        private string especializacionField;
    
        /// <comentarios/>
        public string Especializacion {
            get {
                return this.especializacionField;
            }
            set {
                this.especializacionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void AgregarCirugiaPersonalQCompletedEventHandler(object sender, AgregarCirugiaPersonalQCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarCirugiaPersonalQCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
        private object[] results;
    
        internal AgregarCirugiaPersonalQCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
            this.results = results;
            }
    
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void ObtenerPersonalQCompletedEventHandler(object sender, ObtenerPersonalQCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerPersonalQCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
        private object[] results;
    
        internal ObtenerPersonalQCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
            this.results = results;
            }
    
        /// <remarks/>
        public Personal[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Personal[])(this.results[0]));
            }
        }
    }
}