//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 
namespace Proxy.ProxyCirugiaCirujano {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioCirugiaCirujanoSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProxyCirugia.Entidad))]
    public partial class ServicioCirugiaCirujano : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObtenerCirugiaCirujanoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerCirugiasCirujanoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditarCirugiaCirujanoOperationCompleted;
        
        /// <remarks/>
        public ServicioCirugiaCirujano() {
            this.Url = "http://190.200.157.130/ServiciosCeclimi/ServicioCirugiaCirujano.asmx";
        }
        
        /// <remarks/>
        public event ObtenerCirugiaCirujanoCompletedEventHandler ObtenerCirugiaCirujanoCompleted;
        
        /// <remarks/>
        public event ObtenerCirugiasCirujanoCompletedEventHandler ObtenerCirugiasCirujanoCompleted;
        
        /// <remarks/>
        public event EditarCirugiaCirujanoCompletedEventHandler EditarCirugiaCirujanoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerCirugiaCirujano", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float ObtenerCirugiaCirujano(ProxyCirugia.Cirugia cirugia, Cirujano cirujano) {
            object[] results = this.Invoke("ObtenerCirugiaCirujano", new object[] {
                        cirugia,
                        cirujano});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginObtenerCirugiaCirujano(ProxyCirugia.Cirugia cirugia, Cirujano cirujano, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ObtenerCirugiaCirujano", new object[] {
                        cirugia,
                        cirujano}, callback, asyncState);
        }
        
        /// <remarks/>
        public float EndObtenerCirugiaCirujano(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerCirugiaCirujanoAsync(ProxyCirugia.Cirugia cirugia, Cirujano cirujano) {
            this.ObtenerCirugiaCirujanoAsync(cirugia, cirujano, null);
        }
        
        /// <remarks/>
        public void ObtenerCirugiaCirujanoAsync(ProxyCirugia.Cirugia cirugia, Cirujano cirujano, object userState) {
            if ((this.ObtenerCirugiaCirujanoOperationCompleted == null)) {
                this.ObtenerCirugiaCirujanoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCirugiaCirujanoOperationCompleted);
            }
            this.InvokeAsync("ObtenerCirugiaCirujano", new object[] {
                        cirugia,
                        cirujano}, this.ObtenerCirugiaCirujanoOperationCompleted, userState);
        }
        
        private void OnObtenerCirugiaCirujanoOperationCompleted(object arg) {
            if ((this.ObtenerCirugiaCirujanoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCirugiaCirujanoCompleted(this, new ObtenerCirugiaCirujanoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerCirugiasCirujano", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CirugiaCirujano[] ObtenerCirugiasCirujano(int cedula) {
            object[] results = this.Invoke("ObtenerCirugiasCirujano", new object[] {
                        cedula});
            return ((CirugiaCirujano[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginObtenerCirugiasCirujano(int cedula, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ObtenerCirugiasCirujano", new object[] {
                        cedula}, callback, asyncState);
        }
        
        /// <remarks/>
        public CirugiaCirujano[] EndObtenerCirugiasCirujano(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CirugiaCirujano[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerCirugiasCirujanoAsync(int cedula) {
            this.ObtenerCirugiasCirujanoAsync(cedula, null);
        }
        
        /// <remarks/>
        public void ObtenerCirugiasCirujanoAsync(int cedula, object userState) {
            if ((this.ObtenerCirugiasCirujanoOperationCompleted == null)) {
                this.ObtenerCirugiasCirujanoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCirugiasCirujanoOperationCompleted);
            }
            this.InvokeAsync("ObtenerCirugiasCirujano", new object[] {
                        cedula}, this.ObtenerCirugiasCirujanoOperationCompleted, userState);
        }
        
        private void OnObtenerCirugiasCirujanoOperationCompleted(object arg) {
            if ((this.ObtenerCirugiasCirujanoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCirugiasCirujanoCompleted(this, new ObtenerCirugiasCirujanoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EditarCirugiaCirujano", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EditarCirugiaCirujano(float honorario, int cirugia, int cirujano) {
            object[] results = this.Invoke("EditarCirugiaCirujano", new object[] {
                        honorario,
                        cirugia,
                        cirujano});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEditarCirugiaCirujano(float honorario, int cirugia, int cirujano, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EditarCirugiaCirujano", new object[] {
                        honorario,
                        cirugia,
                        cirujano}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndEditarCirugiaCirujano(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EditarCirugiaCirujanoAsync(float honorario, int cirugia, int cirujano) {
            this.EditarCirugiaCirujanoAsync(honorario, cirugia, cirujano, null);
        }
        
        /// <remarks/>
        public void EditarCirugiaCirujanoAsync(float honorario, int cirugia, int cirujano, object userState) {
            if ((this.EditarCirugiaCirujanoOperationCompleted == null)) {
                this.EditarCirugiaCirujanoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditarCirugiaCirujanoOperationCompleted);
            }
            this.InvokeAsync("EditarCirugiaCirujano", new object[] {
                        honorario,
                        cirugia,
                        cirujano}, this.EditarCirugiaCirujanoOperationCompleted, userState);
        }
        
        private void OnEditarCirugiaCirujanoOperationCompleted(object arg) {
            if ((this.EditarCirugiaCirujanoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditarCirugiaCirujanoCompleted(this, new EditarCirugiaCirujanoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cirugia : ProxyCirugia.Entidad {
        
        private string descripcionField;
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CirugiaCirujano))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Persona))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cirujano))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProxyCirugia.Cirugia))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Entidad {
        
        private long idField;
        
        private string nombreField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CirugiaCirujano : ProxyCirugia.Entidad {
        
        private float honorariosField;
        
        private Cirugia cirugiaField;
        
        private Cirujano cirujanoField;
        
        /// <remarks/>
        public float Honorarios {
            get {
                return this.honorariosField;
            }
            set {
                this.honorariosField = value;
            }
        }
        
        /// <remarks/>
        public Cirugia Cirugia {
            get {
                return this.cirugiaField;
            }
            set {
                this.cirugiaField = value;
            }
        }
        
        /// <remarks/>
        public Cirujano Cirujano {
            get {
                return this.cirujanoField;
            }
            set {
                this.cirujanoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cirujano : Persona {
        
        private string telefonoMovilField;
        
        private string telefonoFijoField;
        
        /// <remarks/>
        public string TelefonoMovil {
            get {
                return this.telefonoMovilField;
            }
            set {
                this.telefonoMovilField = value;
            }
        }
        
        /// <remarks/>
        public string TelefonoFijo {
            get {
                return this.telefonoFijoField;
            }
            set {
                this.telefonoFijoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cirujano))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Persona : ProxyCirugia.Entidad {
        
        private long cedulaField;
        
        private string segundoNombreField;
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        private string telefonoField;
        
        private string correoField;
        
        /// <remarks/>
        public long Cedula {
            get {
                return this.cedulaField;
            }
            set {
                this.cedulaField = value;
            }
        }
        
        /// <remarks/>
        public string SegundoNombre {
            get {
                return this.segundoNombreField;
            }
            set {
                this.segundoNombreField = value;
            }
        }
        
        /// <remarks/>
        public string PrimerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
            }
        }
        
        /// <remarks/>
        public string SegundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void ObtenerCirugiaCirujanoCompletedEventHandler(object sender, ObtenerCirugiaCirujanoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerCirugiaCirujanoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerCirugiaCirujanoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void ObtenerCirugiasCirujanoCompletedEventHandler(object sender, ObtenerCirugiasCirujanoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerCirugiasCirujanoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerCirugiasCirujanoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CirugiaCirujano[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CirugiaCirujano[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void EditarCirugiaCirujanoCompletedEventHandler(object sender, EditarCirugiaCirujanoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditarCirugiaCirujanoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditarCirugiaCirujanoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}
