//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 

namespace Proxy.ProxyCirugia
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioCirugiaSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Entidad))]
    public partial class ServicioCirugia : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AgregarCirugiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerCirugiasOperationCompleted;
        
        /// <remarks/>
        public ServicioCirugia() {
            this.Url = "http://190.200.157.130/ServiciosCeclimi/ServicioCirugia.asmx";
        }
        
        /// <remarks/>
        public event Entidad.AgregarCirugiaCompletedEventHandler AgregarCirugiaCompleted;
        
        /// <remarks/>
        public event Entidad.ObtenerCirugiasCompletedEventHandler ObtenerCirugiasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarCirugia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long AgregarCirugia(Cirugia cirugia) {
            object[] results = this.Invoke("AgregarCirugia", new object[] {
                                                                              cirugia});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAgregarCirugia(Cirugia cirugia, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AgregarCirugia", new object[] {
                                                                       cirugia}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndAgregarCirugia(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarCirugiaAsync(Cirugia cirugia) {
            this.AgregarCirugiaAsync(cirugia, null);
        }
        
        /// <remarks/>
        public void AgregarCirugiaAsync(Cirugia cirugia, object userState) {
            if ((this.AgregarCirugiaOperationCompleted == null)) {
                this.AgregarCirugiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarCirugiaOperationCompleted);
            }
            this.InvokeAsync("AgregarCirugia", new object[] {
                                                                cirugia}, this.AgregarCirugiaOperationCompleted, userState);
        }
        
        private void OnAgregarCirugiaOperationCompleted(object arg) {
            if ((this.AgregarCirugiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarCirugiaCompleted(this, new Entidad.AgregarCirugiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerCirugias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cirugia[] ObtenerCirugias() {
            object[] results = this.Invoke("ObtenerCirugias", new object[0]);
            return ((Cirugia[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginObtenerCirugias(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ObtenerCirugias", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public Cirugia[] EndObtenerCirugias(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Cirugia[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerCirugiasAsync() {
            this.ObtenerCirugiasAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerCirugiasAsync(object userState) {
            if ((this.ObtenerCirugiasOperationCompleted == null)) {
                this.ObtenerCirugiasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCirugiasOperationCompleted);
            }
            this.InvokeAsync("ObtenerCirugias", new object[0], this.ObtenerCirugiasOperationCompleted, userState);
        }
        
        private void OnObtenerCirugiasOperationCompleted(object arg) {
            if ((this.ObtenerCirugiasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCirugiasCompleted(this, new Entidad.ObtenerCirugiasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cirugia : Entidad {
        
        private string descripcionField;
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cirugia))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Entidad {
    private long idField;
        
    private string nombreField;
        
    /// <remarks/>
    public long Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
        
    /// <remarks/>
    public string Nombre {
        get {
            return this.nombreField;
        }
        set {
            this.nombreField = value;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void AgregarCirugiaCompletedEventHandler(object sender, AgregarCirugiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarCirugiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarCirugiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
            this.results = results;
            }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void ObtenerCirugiasCompletedEventHandler(object sender, ObtenerCirugiasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerCirugiasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerCirugiasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
            this.results = results;
            }
        
        /// <remarks/>
        public Cirugia[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cirugia[])(this.results[0]));
            }
        }
    }
}
}