//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.4927
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

namespace Proxy.ProxyCirugiaPaqueteFinanciero
{ // 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioCirugiaPaqueteFinancieroSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Entidad))]
    public partial class ServicioCirugiaPaqueteFinanciero : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
        private System.Threading.SendOrPostCallback AgregarCirugiaPaqueteOperationCompleted;
    
        private System.Threading.SendOrPostCallback EliminarCirugiaPaqueteOperationCompleted;
    
        /// <remarks/>
        public ServicioCirugiaPaqueteFinanciero() {
            this.Url = "http://192.168.1.109/ServiciosCeclimi/ServicioCirugiaPaqueteFinanciero.asmx";
        }
    
        /// <remarks/>
        public event AgregarCirugiaPaqueteCompletedEventHandler AgregarCirugiaPaqueteCompleted;
    
        /// <remarks/>
        public event EliminarCirugiaPaqueteCompletedEventHandler EliminarCirugiaPaqueteCompleted;
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarCirugiaPaquete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AgregarCirugiaPaquete(CirugiaPqtFinanciero cirugiaPqtFinanciero) {
            object[] results = this.Invoke("AgregarCirugiaPaquete", new object[] {
                                                                                     cirugiaPqtFinanciero});
            return ((int)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BeginAgregarCirugiaPaquete(CirugiaPqtFinanciero cirugiaPqtFinanciero, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AgregarCirugiaPaquete", new object[] {
                                                                              cirugiaPqtFinanciero}, callback, asyncState);
        }
    
        /// <remarks/>
        public int EndAgregarCirugiaPaquete(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
    
        /// <remarks/>
        public void AgregarCirugiaPaqueteAsync(CirugiaPqtFinanciero cirugiaPqtFinanciero) {
            this.AgregarCirugiaPaqueteAsync(cirugiaPqtFinanciero, null);
        }
    
        /// <remarks/>
        public void AgregarCirugiaPaqueteAsync(CirugiaPqtFinanciero cirugiaPqtFinanciero, object userState) {
            if ((this.AgregarCirugiaPaqueteOperationCompleted == null)) {
                this.AgregarCirugiaPaqueteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarCirugiaPaqueteOperationCompleted);
            }
            this.InvokeAsync("AgregarCirugiaPaquete", new object[] {
                                                                       cirugiaPqtFinanciero}, this.AgregarCirugiaPaqueteOperationCompleted, userState);
        }
    
        private void OnAgregarCirugiaPaqueteOperationCompleted(object arg) {
            if ((this.AgregarCirugiaPaqueteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarCirugiaPaqueteCompleted(this, new AgregarCirugiaPaqueteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarCirugiaPaquete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarCirugiaPaquete(int id) {
            object[] results = this.Invoke("EliminarCirugiaPaquete", new object[] {
                                                                                      id});
            return ((bool)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BeginEliminarCirugiaPaquete(int id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EliminarCirugiaPaquete", new object[] {
                                                                               id}, callback, asyncState);
        }
    
        /// <remarks/>
        public bool EndEliminarCirugiaPaquete(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    
        /// <remarks/>
        public void EliminarCirugiaPaqueteAsync(int id) {
            this.EliminarCirugiaPaqueteAsync(id, null);
        }
    
        /// <remarks/>
        public void EliminarCirugiaPaqueteAsync(int id, object userState) {
            if ((this.EliminarCirugiaPaqueteOperationCompleted == null)) {
                this.EliminarCirugiaPaqueteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarCirugiaPaqueteOperationCompleted);
            }
            this.InvokeAsync("EliminarCirugiaPaquete", new object[] {
                                                                        id}, this.EliminarCirugiaPaqueteOperationCompleted, userState);
        }
    
        private void OnEliminarCirugiaPaqueteOperationCompleted(object arg) {
            if ((this.EliminarCirugiaPaqueteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarCirugiaPaqueteCompleted(this, new EliminarCirugiaPaqueteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CirugiaPqtFinanciero : Entidad {
    
        private float montoCirujanoField;
    
        private float descuentoField;
    
        private Cirujano cirujanoField;
    
        private System.DateTime fechaOperacionField;
    
        private Cirugia cirugiaField;
    
        private PaqueteFinanciero paqueteFinancieroField;
    
        private float protesisField;
    
        /// <comentarios/>
        public float MontoCirujano {
            get {
                return this.montoCirujanoField;
            }
            set {
                this.montoCirujanoField = value;
            }
        }
    
        /// <comentarios/>
        public float Descuento {
            get {
                return this.descuentoField;
            }
            set {
                this.descuentoField = value;
            }
        }
    
        /// <comentarios/>
        public Cirujano Cirujano {
            get {
                return this.cirujanoField;
            }
            set {
                this.cirujanoField = value;
            }
        }
    
        /// <comentarios/>
        public System.DateTime FechaOperacion {
            get {
                return this.fechaOperacionField;
            }
            set {
                this.fechaOperacionField = value;
            }
        }
    
        /// <comentarios/>
        public Cirugia Cirugia {
            get {
                return this.cirugiaField;
            }
            set {
                this.cirugiaField = value;
            }
        }
    
        /// <comentarios/>
        public PaqueteFinanciero PaqueteFinanciero {
            get {
                return this.paqueteFinancieroField;
            }
            set {
                this.paqueteFinancieroField = value;
            }
        }
    
        /// <comentarios/>
        public float Protesis {
            get {
                return this.protesisField;
            }
            set {
                this.protesisField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cirujano : Persona {
    
        private string telefonoMovilField;
    
        private string telefonoFijoField;
    
        /// <comentarios/>
        public string TelefonoMovil {
            get {
                return this.telefonoMovilField;
            }
            set {
                this.telefonoMovilField = value;
            }
        }
    
        /// <comentarios/>
        public string TelefonoFijo {
            get {
                return this.telefonoFijoField;
            }
            set {
                this.telefonoFijoField = value;
            }
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cirujano))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Paciente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Persona : Entidad {
    
        private long cedulaField;
    
        private string segundoNombreField;
    
        private string primerApellidoField;
    
        private string segundoApellidoField;
    
        private string telefonoField;
    
        private string correoField;
    
        /// <comentarios/>
        public long Cedula {
            get {
                return this.cedulaField;
            }
            set {
                this.cedulaField = value;
            }
        }
    
        /// <comentarios/>
        public string SegundoNombre {
            get {
                return this.segundoNombreField;
            }
            set {
                this.segundoNombreField = value;
            }
        }
    
        /// <comentarios/>
        public string PrimerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
            }
        }
    
        /// <comentarios/>
        public string SegundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
            }
        }
    
        /// <comentarios/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
    
        /// <comentarios/>
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PaqueteFinanciero))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cirugia))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Persona))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cirujano))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Paciente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CirugiaPqtFinanciero))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Entidad {
    
        private long idField;
    
        private string nombreField;
    
        /// <comentarios/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PaqueteFinanciero : Entidad {
    
        private System.DateTime fechaPaqueteField;
    
        private System.DateTime fechaLimiteField;
    
        private Paciente pacienteField;
    
        /// <comentarios/>
        public System.DateTime FechaPaquete {
            get {
                return this.fechaPaqueteField;
            }
            set {
                this.fechaPaqueteField = value;
            }
        }
    
        /// <comentarios/>
        public System.DateTime FechaLimite {
            get {
                return this.fechaLimiteField;
            }
            set {
                this.fechaLimiteField = value;
            }
        }
    
        /// <comentarios/>
        public Paciente Paciente {
            get {
                return this.pacienteField;
            }
            set {
                this.pacienteField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Paciente : Persona {
    
        private System.DateTime fechaIngresoField;
    
        private string telefonoMovilField;
    
        /// <comentarios/>
        public System.DateTime FechaIngreso {
            get {
                return this.fechaIngresoField;
            }
            set {
                this.fechaIngresoField = value;
            }
        }
    
        /// <comentarios/>
        public string TelefonoMovil {
            get {
                return this.telefonoMovilField;
            }
            set {
                this.telefonoMovilField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cirugia : Entidad {
    
        private string descripcionField;
    
        /// <comentarios/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void AgregarCirugiaPaqueteCompletedEventHandler(object sender, AgregarCirugiaPaqueteCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarCirugiaPaqueteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
        private object[] results;
    
        internal AgregarCirugiaPaqueteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
            this.results = results;
            }
    
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void EliminarCirugiaPaqueteCompletedEventHandler(object sender, EliminarCirugiaPaqueteCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarCirugiaPaqueteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
        private object[] results;
    
        internal EliminarCirugiaPaqueteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
            this.results = results;
            }
    
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}