//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.4927
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

namespace Proxy.ProxyPagos
{ // 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioPagosSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Entidad))]
    public partial class ServicioPagos : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
        private System.Threading.SendOrPostCallback AgregarPagosOperationCompleted;
    
        private System.Threading.SendOrPostCallback ObtenerPagosPacienteOperationCompleted;
    
        private System.Threading.SendOrPostCallback ValidarPagoExistenteOperationCompleted;
    
        /// <remarks/>
        public ServicioPagos() {
            this.Url = "http://192.168.1.109/ServiciosCeclimi/ServicioPagos.asmx";
        }
    
        /// <remarks/>
        public event AgregarPagosCompletedEventHandler AgregarPagosCompleted;
    
        /// <remarks/>
        public event ObtenerPagosPacienteCompletedEventHandler ObtenerPagosPacienteCompleted;
    
        /// <remarks/>
        public event ValidarPagoExistenteCompletedEventHandler ValidarPagoExistenteCompleted;
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarPagos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AgregarPagos(Pago pago) {
            object[] results = this.Invoke("AgregarPagos", new object[] {
                                                                            pago});
            return ((bool)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BeginAgregarPagos(Pago pago, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AgregarPagos", new object[] {
                                                                     pago}, callback, asyncState);
        }
    
        /// <remarks/>
        public bool EndAgregarPagos(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    
        /// <remarks/>
        public void AgregarPagosAsync(Pago pago) {
            this.AgregarPagosAsync(pago, null);
        }
    
        /// <remarks/>
        public void AgregarPagosAsync(Pago pago, object userState) {
            if ((this.AgregarPagosOperationCompleted == null)) {
                this.AgregarPagosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarPagosOperationCompleted);
            }
            this.InvokeAsync("AgregarPagos", new object[] {
                                                              pago}, this.AgregarPagosOperationCompleted, userState);
        }
    
        private void OnAgregarPagosOperationCompleted(object arg) {
            if ((this.AgregarPagosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarPagosCompleted(this, new AgregarPagosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerPagosPaciente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pago[] ObtenerPagosPaciente(Paciente paciente) {
            object[] results = this.Invoke("ObtenerPagosPaciente", new object[] {
                                                                                    paciente});
            return ((Pago[])(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BeginObtenerPagosPaciente(Paciente paciente, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ObtenerPagosPaciente", new object[] {
                                                                             paciente}, callback, asyncState);
        }
    
        /// <remarks/>
        public Pago[] EndObtenerPagosPaciente(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Pago[])(results[0]));
        }
    
        /// <remarks/>
        public void ObtenerPagosPacienteAsync(Paciente paciente) {
            this.ObtenerPagosPacienteAsync(paciente, null);
        }
    
        /// <remarks/>
        public void ObtenerPagosPacienteAsync(Paciente paciente, object userState) {
            if ((this.ObtenerPagosPacienteOperationCompleted == null)) {
                this.ObtenerPagosPacienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPagosPacienteOperationCompleted);
            }
            this.InvokeAsync("ObtenerPagosPaciente", new object[] {
                                                                      paciente}, this.ObtenerPagosPacienteOperationCompleted, userState);
        }
    
        private void OnObtenerPagosPacienteOperationCompleted(object arg) {
            if ((this.ObtenerPagosPacienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerPagosPacienteCompleted(this, new ObtenerPagosPacienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidarPagoExistente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ValidarPagoExistente(int idpago) {
            object[] results = this.Invoke("ValidarPagoExistente", new object[] {
                                                                                    idpago});
            return ((int)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BeginValidarPagoExistente(int idpago, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ValidarPagoExistente", new object[] {
                                                                             idpago}, callback, asyncState);
        }
    
        /// <remarks/>
        public int EndValidarPagoExistente(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
    
        /// <remarks/>
        public void ValidarPagoExistenteAsync(int idpago) {
            this.ValidarPagoExistenteAsync(idpago, null);
        }
    
        /// <remarks/>
        public void ValidarPagoExistenteAsync(int idpago, object userState) {
            if ((this.ValidarPagoExistenteOperationCompleted == null)) {
                this.ValidarPagoExistenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarPagoExistenteOperationCompleted);
            }
            this.InvokeAsync("ValidarPagoExistente", new object[] {
                                                                      idpago}, this.ValidarPagoExistenteOperationCompleted, userState);
        }
    
        private void OnValidarPagoExistenteOperationCompleted(object arg) {
            if ((this.ValidarPagoExistenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarPagoExistenteCompleted(this, new ValidarPagoExistenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Pago : Entidad {
    
        private string tipoPagoField;
    
        private string seguroField;
    
        private System.DateTime fechaField;
    
        private float montoField;
    
        private Persona usuarioField;
    
        /// <comentarios/>
        public string TipoPago {
            get {
                return this.tipoPagoField;
            }
            set {
                this.tipoPagoField = value;
            }
        }
    
        /// <comentarios/>
        public string Seguro {
            get {
                return this.seguroField;
            }
            set {
                this.seguroField = value;
            }
        }
    
        /// <comentarios/>
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
    
        /// <comentarios/>
        public float Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
    
        /// <comentarios/>
        public Persona Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Paciente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Persona : Entidad {
    
        private long cedulaField;
    
        private string segundoNombreField;
    
        private string primerApellidoField;
    
        private string segundoApellidoField;
    
        private string telefonoField;
    
        private string correoField;
    
        /// <comentarios/>
        public long Cedula {
            get {
                return this.cedulaField;
            }
            set {
                this.cedulaField = value;
            }
        }
    
        /// <comentarios/>
        public string SegundoNombre {
            get {
                return this.segundoNombreField;
            }
            set {
                this.segundoNombreField = value;
            }
        }
    
        /// <comentarios/>
        public string PrimerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
            }
        }
    
        /// <comentarios/>
        public string SegundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
            }
        }
    
        /// <comentarios/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
    
        /// <comentarios/>
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Persona))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Paciente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Pago))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Entidad {
    
        private long idField;
    
        private string nombreField;
    
        /// <comentarios/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Paciente : Persona {
    
        private System.DateTime fechaIngresoField;
    
        private string telefonoMovilField;
    
        /// <comentarios/>
        public System.DateTime FechaIngreso {
            get {
                return this.fechaIngresoField;
            }
            set {
                this.fechaIngresoField = value;
            }
        }
    
        /// <comentarios/>
        public string TelefonoMovil {
            get {
                return this.telefonoMovilField;
            }
            set {
                this.telefonoMovilField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void AgregarPagosCompletedEventHandler(object sender, AgregarPagosCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarPagosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
        private object[] results;
    
        internal AgregarPagosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
            this.results = results;
            }
    
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void ObtenerPagosPacienteCompletedEventHandler(object sender, ObtenerPagosPacienteCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerPagosPacienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
        private object[] results;
    
        internal ObtenerPagosPacienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
            this.results = results;
            }
    
        /// <remarks/>
        public Pago[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pago[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void ValidarPagoExistenteCompletedEventHandler(object sender, ValidarPagoExistenteCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarPagoExistenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
        private object[] results;
    
        internal ValidarPagoExistenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
            this.results = results;
            }
    
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}