//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 

namespace Proxy.ProxyTransferencia {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioTransferenciaSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Entidad))]
    public partial class ServicioTransferencia : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AgregarTransferenciaOperationCompleted;
        
        /// <remarks/>
        public ServicioTransferencia() {
            this.Url = "http://190.200.157.130/ServiciosCeclimi/ServicioTransferencia.asmx";
        }
        
        /// <remarks/>
        public event AgregarTransferenciaCompletedEventHandler AgregarTransferenciaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarTransferencia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AgregarTransferencia(Transferencia transferencia) {
            object[] results = this.Invoke("AgregarTransferencia", new object[] {
                        transferencia});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAgregarTransferencia(Transferencia transferencia, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AgregarTransferencia", new object[] {
                        transferencia}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndAgregarTransferencia(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarTransferenciaAsync(Transferencia transferencia) {
            this.AgregarTransferenciaAsync(transferencia, null);
        }
        
        /// <remarks/>
        public void AgregarTransferenciaAsync(Transferencia transferencia, object userState) {
            if ((this.AgregarTransferenciaOperationCompleted == null)) {
                this.AgregarTransferenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarTransferenciaOperationCompleted);
            }
            this.InvokeAsync("AgregarTransferencia", new object[] {
                        transferencia}, this.AgregarTransferenciaOperationCompleted, userState);
        }
        
        private void OnAgregarTransferenciaOperationCompleted(object arg) {
            if ((this.AgregarTransferenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarTransferenciaCompleted(this, new AgregarTransferenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Transferencia : Entidad {
        
        private float montoField;
        
        private Persona pacienteOtorgaField;
        
        private Persona pacienteRecibeField;
        
        /// <remarks/>
        public float Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        public Persona PacienteOtorga {
            get {
                return this.pacienteOtorgaField;
            }
            set {
                this.pacienteOtorgaField = value;
            }
        }
        
        /// <remarks/>
        public Persona PacienteRecibe {
            get {
                return this.pacienteRecibeField;
            }
            set {
                this.pacienteRecibeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Persona : Entidad {
        
        private long cedulaField;
        
        private string segundoNombreField;
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        private string telefonoField;
        
        private string correoField;
        
        /// <remarks/>
        public long Cedula {
            get {
                return this.cedulaField;
            }
            set {
                this.cedulaField = value;
            }
        }
        
        /// <remarks/>
        public string SegundoNombre {
            get {
                return this.segundoNombreField;
            }
            set {
                this.segundoNombreField = value;
            }
        }
        
        /// <remarks/>
        public string PrimerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
            }
        }
        
        /// <remarks/>
        public string SegundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Persona))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Transferencia))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Entidad {
        
        private long idField;
        
        private string nombreField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void AgregarTransferenciaCompletedEventHandler(object sender, AgregarTransferenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarTransferenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarTransferenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}
