//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.4927
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

namespace Proxy.ProxyCirujano
{ // 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioCirujanoSoap", Namespace="http://tempuri.org/")]
    public partial class ServicioCirujano : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
        private System.Threading.SendOrPostCallback ObtenerCirujanosOperationCompleted;
    
        private System.Threading.SendOrPostCallback ObtenerInformacionCirujanoOperationCompleted;
    
        private System.Threading.SendOrPostCallback EditarCirujanoOperationCompleted;
    
        /// <remarks/>
        public ServicioCirujano() {
            this.Url = "http://192.168.1.109/ServiciosCeclimi/ServicioCirujano.asmx";
        }
    
        /// <remarks/>
        public event ObtenerCirujanosCompletedEventHandler ObtenerCirujanosCompleted;
    
        /// <remarks/>
        public event ObtenerInformacionCirujanoCompletedEventHandler ObtenerInformacionCirujanoCompleted;
    
        /// <remarks/>
        public event EditarCirujanoCompletedEventHandler EditarCirujanoCompleted;
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerCirujanos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cirujano[] ObtenerCirujanos(Entidad cirugia) {
            object[] results = this.Invoke("ObtenerCirujanos", new object[] {
                                                                                cirugia});
            return ((Cirujano[])(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BeginObtenerCirujanos(Entidad cirugia, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ObtenerCirujanos", new object[] {
                                                                         cirugia}, callback, asyncState);
        }
    
        /// <remarks/>
        public Cirujano[] EndObtenerCirujanos(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Cirujano[])(results[0]));
        }
    
        /// <remarks/>
        public void ObtenerCirujanosAsync(Entidad cirugia) {
            this.ObtenerCirujanosAsync(cirugia, null);
        }
    
        /// <remarks/>
        public void ObtenerCirujanosAsync(Entidad cirugia, object userState) {
            if ((this.ObtenerCirujanosOperationCompleted == null)) {
                this.ObtenerCirujanosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCirujanosOperationCompleted);
            }
            this.InvokeAsync("ObtenerCirujanos", new object[] {
                                                                  cirugia}, this.ObtenerCirujanosOperationCompleted, userState);
        }
    
        private void OnObtenerCirujanosOperationCompleted(object arg) {
            if ((this.ObtenerCirujanosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCirujanosCompleted(this, new ObtenerCirujanosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerInformacionCirujano", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cirujano ObtenerInformacionCirujano(int cedula) {
            object[] results = this.Invoke("ObtenerInformacionCirujano", new object[] {
                                                                                          cedula});
            return ((Cirujano)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BeginObtenerInformacionCirujano(int cedula, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ObtenerInformacionCirujano", new object[] {
                                                                                   cedula}, callback, asyncState);
        }
    
        /// <remarks/>
        public Cirujano EndObtenerInformacionCirujano(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Cirujano)(results[0]));
        }
    
        /// <remarks/>
        public void ObtenerInformacionCirujanoAsync(int cedula) {
            this.ObtenerInformacionCirujanoAsync(cedula, null);
        }
    
        /// <remarks/>
        public void ObtenerInformacionCirujanoAsync(int cedula, object userState) {
            if ((this.ObtenerInformacionCirujanoOperationCompleted == null)) {
                this.ObtenerInformacionCirujanoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerInformacionCirujanoOperationCompleted);
            }
            this.InvokeAsync("ObtenerInformacionCirujano", new object[] {
                                                                            cedula}, this.ObtenerInformacionCirujanoOperationCompleted, userState);
        }
    
        private void OnObtenerInformacionCirujanoOperationCompleted(object arg) {
            if ((this.ObtenerInformacionCirujanoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerInformacionCirujanoCompleted(this, new ObtenerInformacionCirujanoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EditarCirujano", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EditarCirujano(Cirujano cirujano) {
            object[] results = this.Invoke("EditarCirujano", new object[] {
                                                                              cirujano});
            return ((bool)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BeginEditarCirujano(Cirujano cirujano, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EditarCirujano", new object[] {
                                                                       cirujano}, callback, asyncState);
        }
    
        /// <remarks/>
        public bool EndEditarCirujano(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    
        /// <remarks/>
        public void EditarCirujanoAsync(Cirujano cirujano) {
            this.EditarCirujanoAsync(cirujano, null);
        }
    
        /// <remarks/>
        public void EditarCirujanoAsync(Cirujano cirujano, object userState) {
            if ((this.EditarCirujanoOperationCompleted == null)) {
                this.EditarCirujanoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditarCirujanoOperationCompleted);
            }
            this.InvokeAsync("EditarCirujano", new object[] {
                                                                cirujano}, this.EditarCirujanoOperationCompleted, userState);
        }
    
        private void OnEditarCirujanoOperationCompleted(object arg) {
            if ((this.EditarCirujanoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditarCirujanoCompleted(this, new EditarCirujanoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Persona))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cirujano))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Entidad {
    
        private long idField;
    
        private string nombreField;
    
        /// <comentarios/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cirujano))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Persona : Entidad {
    
        private long cedulaField;
    
        private string segundoNombreField;
    
        private string primerApellidoField;
    
        private string segundoApellidoField;
    
        private string telefonoField;
    
        private string correoField;
    
        /// <comentarios/>
        public long Cedula {
            get {
                return this.cedulaField;
            }
            set {
                this.cedulaField = value;
            }
        }
    
        /// <comentarios/>
        public string SegundoNombre {
            get {
                return this.segundoNombreField;
            }
            set {
                this.segundoNombreField = value;
            }
        }
    
        /// <comentarios/>
        public string PrimerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
            }
        }
    
        /// <comentarios/>
        public string SegundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
            }
        }
    
        /// <comentarios/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
    
        /// <comentarios/>
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cirujano : Persona {
    
        private string telefonoMovilField;
    
        private string telefonoFijoField;
    
        /// <comentarios/>
        public string TelefonoMovil {
            get {
                return this.telefonoMovilField;
            }
            set {
                this.telefonoMovilField = value;
            }
        }
    
        /// <comentarios/>
        public string TelefonoFijo {
            get {
                return this.telefonoFijoField;
            }
            set {
                this.telefonoFijoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void ObtenerCirujanosCompletedEventHandler(object sender, ObtenerCirujanosCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerCirujanosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
        private object[] results;
    
        internal ObtenerCirujanosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
            this.results = results;
            }
    
        /// <remarks/>
        public Cirujano[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cirujano[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void ObtenerInformacionCirujanoCompletedEventHandler(object sender, ObtenerInformacionCirujanoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerInformacionCirujanoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
        private object[] results;
    
        internal ObtenerInformacionCirujanoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
            this.results = results;
            }
    
        /// <remarks/>
        public Cirujano Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cirujano)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void EditarCirujanoCompletedEventHandler(object sender, EditarCirujanoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditarCirujanoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
        private object[] results;
    
        internal EditarCirujanoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
            this.results = results;
            }
    
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}